# X11 default option to be able to test the result in the browser
image:
  file: .gitpod.Dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview

tasks:

  - name: actual building and running of hotspot
    #before: gp preview "$(gp url 6080)"
    init: |
      mkdir -p build
      cd build
      cmake -DCMAKE_INSTALL_PREFIX=/opt/KDAB -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..
      nice make -j $(nproc)
    command: |
      export PATH=${GITPOD_REPO_ROOTS}/build/bin:${PATH}
      hotspot $GITPOD_REPO_ROOTS/tests/integrationtests/custom_cost_aggregation_testfiles/custom_cost_aggregation.perfparser

# some config to ease working in the browser
vscode:
  extensions:
    - twxs.cmake
    - llvm-vs-code-extensions.vscode-clangd
    - webfreak.debug
